### ISSUE TITLE
Error Load Burp Extension - Carbonator

### ISSUE THREAD

**Issue by spabam** [integrissecurity/carbonator#4]
java.lang.NoClassDefFoundError: com/google/common/collect/MapMaker
	at org.python.core.PyType.fromClass(PyType.java:1280)
	at org.python.core.PyObject.<init>(PyObject.java:66)
	at org.python.core.PyBuiltinCallable.<init>(PyBuiltinCallable.java:21)
	at org.python.core.PyBuiltinMethod.<init>(PyBuiltinMethod.java:16)
	at org.python.core.PyBuiltinMethodNarrow.<init>(PyBuiltinMethodNarrow.java:24)
	at org.python.core.PyType$type___subclasses___exposer.<init>(Unknown Source)
	at org.python.core.PyType$PyExposer.<init>(Unknown Source)
	at org.python.core.PyType.<clinit>(PyType.java)
	at org.python.core.PyObject.<init>(PyObject.java:66)
	at org.python.core.PyBuiltinCallable.<init>(PyBuiltinCallable.java:21)
	at org.python.core.PyBuiltinMethod.<init>(PyBuiltinMethod.java:16)
	at org.python.core.PyBuiltinMethodNarrow.<init>(PyBuiltinMethodNarrow.java:24)
	at org.python.core.PyDataDescr$getset_descriptor___get___exposer.<init>(Unknown Source)
	at org.python.core.PyDataDescr$PyExposer.<init>(Unknown Source)
	at org.python.core.PyDataDescr.<clinit>(PyDataDescr.java)
	at org.python.core.PyBuiltinCallable$PyExposer.<init>(Unknown Source)
	at org.python.core.PyBuiltinCallable.<clinit>(PyBuiltinCallable.java)
	at org.python.core.PyObject$PyExposer.<init>(Unknown Source)
	at org.python.core.PyObject.<clinit>(PyObject.java)
	at org.python.core.Py.<clinit>(Py.java:537)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:97)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:92)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:64)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at burp.p9b.<init>(Unknown Source)
	at burp.hec.a(Unknown Source)
	at burp.q4c.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.MapMaker
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 31 more

**Comment by spabam** [comment]
Burp Suite 1.6.14 professional
Carbonator from BApp Store as well as latest Carbonator from github
